### ISSUE TITLE
python script has wierd behavior sometimes when pasting endpoint url

### ISSUE THREAD

**Issue by davidanp** [pyxeda/ML-Lessons#109]
It doesnt wait for the 'enter' press and just goes on to the next prompt.

Eventually the program will error out.

<img width="1370" alt="Screen Shot 2019-06-24 at 5 25 08 PM" src="https://user-images.githubusercontent.com/48690797/60060358-148bfe80-96a5-11e9-9d4c-68a87cafde3c.png">

**Comment by davidanp** [comment]
looks like i can 100% recreate this by selecting the endpoint url via a triple click then ctrl+c. Which is odd because i can paste it into a txt file just fine.

EDIT: its because the triple click includes a \n char. its messing with the python script

**Comment by swamisundar** [comment]
@davidanp This is already fixed. This is because of extraneous characters in the url string and has been stripped off now.
