### ISSUE TITLE
Age-project-3-scratch

### ISSUE THREAD

**Issue by sindhuPyxeda** [pyxeda/ML-Lessons#222]
The program asks for urls of smaller and bigger datasets, this is wrong. It should ask for balances and skewed datasets. Same for python

**Comment by swamisundar** [comment]
@sindhuPyxeda The doc doesn't say skewed and balances datasets. Could you please fix the doc? I will fix the code after that.

**Comment by swamisundar** [comment]
Mood Project 4 Python code: 

#calculate and print out the prediction based on ML
def get_prediction(url, data={"sentence:", "I love to help others!"}):
    r = requests.post(url, data=json.dumps(data))
    response = getattr(r,'_content').decode("utf-8")
    response = json.loads(response)
    prediction_object = json.loads(response['body'])
    label = ""
    if 'predicted_label' in prediction_object:
        label = prediction_object['predicted_label']

    print("ML prediction")
    print("\tLabel: ", label)
    print("\tModel: ", prediction_object['Model'])
    print("\tMessage: ", prediction_object['Message'])
    return label

if __name__ == "__main__":
    main()

@sindhuPyxeda  we compare the datasets in project4 python code. Do you want us to add the comparison?

**Comment by swamisundar** [comment]
The same applies to the scratch program too. Its the same as project1 and doesn't ask for small/large datasets.
