### ISSUE TITLE
Mood Project 2 sbx rules engine and docs are not aligned

### ISSUE THREAD

**Issue by davidanp** [pyxeda/ML-Lessons#88]
For example
When the program asks “How are you feeling?” - enter: “I feel fat” 

You should find that the program’s rule engine gives the right answer - Sad
Did the Machine Learning model get the right answer?

Do the same thing for the second data point. Did both approaches get the right answer?

The rules engine in the program is very simple. If the sentence contains the text “fat” or “sad”, it will select “sad”. If not, it will by default select “happy”.

---------

When inspecting the rules engine, its looking for either bad or sad.

**Comment by swamisundar** [comment]
@davidanp why is this a bug?

**Comment by davidanp** [comment]
instructions for the docs for sbx usage are incorrect (or the sbx is incorrect). If you follow the instructions verbatim, it will not work out. That is why it tis a bug.

**Comment by nishatalagala** [comment]
Fixed in doc
